import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { Syne } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/header";
import Footer from "@/components/footer";
const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen", syne.className)}>
        <Header />
        <main className=" relative max-w-[1380px] m-auto mt-[4rem] px-3">
          <div className=" absolute top-0 left-[12px] flex gap-1 font-medium">
            <Link href="#" className=" text-seo-friendly-orange ">
              Home
            </Link>
            /<Link href="#">Products</Link>
          </div>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
